### ISSUE TITLE
Reset password endpoint probably should not return updated user

### ISSUE THREAD

**Issue by SobakaSlava** [paralect/koa-api-starter#66]
Currently reset password endpoint return updated user as response. As result web gets user but doesn't get cookies and the app is redirected to the main layout but all requests fail with 401. After page refresh user is logged out. As proposal `user` should only be returned in `/users/...` endpoints. 
According to this issue it needs to be decided either to set cookies after reset password (if we need auto logging in) or return empty body (if we don't need it and the web will redirect where it's needed on it's own)

**Comment by hovoodd** [comment]
already fixed
