### ISSUE TITLE
Mongo replicator doesn't handle negative scenarios

### ISSUE THREAD

**Issue by AllDayAlone** [paralect/koa-api-starter#67]
If anything wrong with the connection to Mongo (the server didn't start, wrong creds) replicator will still say "Replication Done" and "Mongo is already replicated". And it's not correct.

Suggestion:
Make the script smarter, add reconnect trials and negative exit

**Comment by hovoodd** [comment]
https://github.com/paralect/koa-api-starter/pull/69

**Comment by hovoodd** [comment]
Fixed: https://github.com/paralect/koa-api-starter/pull/69
